possible_latin_chars = {
    "a": "a",  # LATIN SMALL LETTER A > LATIN SMALL LETTER A
    "i": "i",  # LATIN SMALL LETTER I > LATIN SMALL LETTER I
    "e": "e",  # LATIN SMALL LETTER E > LATIN SMALL LETTER E
    "n": "n",  # LATIN SMALL LETTER N > LATIN SMALL LETTER N
    "l": "l",  # LATIN SMALL LETTER L > LATIN SMALL LETTER L
    "r": "r",  # LATIN SMALL LETTER R > LATIN SMALL LETTER R
    "m": "m",  # LATIN SMALL LETTER M > LATIN SMALL LETTER M
    "d": "d",  # LATIN SMALL LETTER D > LATIN SMALL LETTER D
    "ı": "ı",  # LATIN SMALL LETTER DOTLESS I > LATIN SMALL LETTER I
    "s": "s",  # LATIN SMALL LETTER S > LATIN SMALL LETTER S
    "k": "k",  # LATIN SMALL LETTER K > LATIN SMALL LETTER K
    "t": "t",  # LATIN SMALL LETTER T > LATIN SMALL LETTER T
    "y": "y",  # LATIN SMALL LETTER Y > LATIN SMALL LETTER Y
    "u": "u",  # LATIN SMALL LETTER U > LATIN SMALL LETTER U
    "o": "o",  # LATIN SMALL LETTER O > LATIN SMALL LETTER O
    "z": "z",  # LATIN SMALL LETTER Z > LATIN SMALL LETTER Z
    "b": "b",  # LATIN SMALL LETTER B > LATIN SMALL LETTER B
    "c": "c",  # LATIN SMALL LETTER C > LATIN SMALL LETTER C
    "h": "h",  # LATIN SMALL LETTER H > LATIN SMALL LETTER H
    "g": "g",  # LATIN SMALL LETTER G > LATIN SMALL LETTER G
    "ş": "ş",  # LATIN SMALL LETTER S WITH CEDILLA > LATIN SMALL LETTER S WITH CEDILLA
    "'": "'",  # APOSTROPHE > APOSTROPHE
    "ü": "ü",  # LATIN SMALL LETTER U WITH DIAERESIS > LATIN SMALL LETTER U
    "p": "p",  # LATIN SMALL LETTER P > LATIN SMALL LETTER P
    "j": "j",  # LATIN SMALL LETTER J > LATIN SMALL LETTER J
    "f": "f",  # LATIN SMALL LETTER F > LATIN SMALL LETTER F
    "ğ": "ğ",  # LATIN SMALL LETTER G WITH BREVE > LATIN SMALL LETTER G
    "v": "v",  # LATIN SMALL LETTER V > LATIN SMALL LETTER V
    "ç": "ç",  # LATIN SMALL LETTER C WITH CEDILLA > LATIN SMALL LETTER C
    "ö": "ö",  # LATIN SMALL LETTER O WITH DIAERESIS > LATIN SMALL LETTER O
    "w": "w",  # LATIN SMALL LETTER W > LATIN SMALL LETTER W
    "x": "x",  # LATIN SMALL LETTER X > LATIN SMALL LETTER X
    "0": "0",  # DIGIT ZERO > DIGIT ZERO
    "q": "q",  # LATIN SMALL LETTER Q > LATIN SMALL LETTER Q
    "1": "1",  # DIGIT ONE > DIGIT ONE
    "2": "2",  # DIGIT TWO > DIGIT TWO
    "3": "3",  # DIGIT THREE > DIGIT THREE
    "5": "5",  # DIGIT FIVE > DIGIT FIVE
    "4": "4",  # DIGIT FOUR > DIGIT FOUR
    "8": "8",  # DIGIT EIGHT > DIGIT EIGHT
    "9": "9",  # DIGIT NINE > DIGIT NINE
    "7": "7",  # DIGIT SEVEN > DIGIT SEVEN
    "ə": "@",  # LATIN SMALL LETTER SCHWA > COMMERCIAL AT
    "6": "6",  # DIGIT SIX > DIGIT SIX
    "â": "a",  # LATIN SMALL LETTER A WITH CIRCUMFLEX > LATIN SMALL LETTER A
    "î": "i",  # LATIN SMALL LETTER I WITH CIRCUMFLEX > LATIN SMALL LETTER I
    "_": "_",  # LOW LINE > LOW LINE
    "ê": "e",  # LATIN SMALL LETTER E WITH CIRCUMFLEX > LATIN SMALL LETTER E
    "ï": "i",  # LATIN SMALL LETTER I WITH DIAERESIS > LATIN SMALL LETTER I
    "é": "e",  # LATIN SMALL LETTER E WITH ACUTE > LATIN SMALL LETTER E
    "û": "u",  # LATIN SMALL LETTER U WITH CIRCUMFLEX > LATIN SMALL LETTER U
    "ý": "y",  # LATIN SMALL LETTER Y WITH ACUTE > LATIN SMALL LETTER Y
    "а": "a",  # CYRILLIC SMALL LETTER A > LATIN SMALL LETTER A
    "ä": "a",  # LATIN SMALL LETTER A WITH DIAERESIS > LATIN SMALL LETTER A
    "ș": "s",  # LATIN SMALL LETTER S WITH COMMA BELOW > LATIN SMALL LETTER S
    "í": "i",  # LATIN SMALL LETTER I WITH ACUTE > LATIN SMALL LETTER I
    "ι": "ı",  # GREEK SMALL LETTER IOTA > LATIN SMALL LETTER DOTLESS I
    "е": "e",  # CYRILLIC SMALL LETTER IE > LATIN SMALL LETTER E
    "ã": "a",  # LATIN SMALL LETTER A WITH TILDE > LATIN SMALL LETTER A
    "ó": "o",  # LATIN SMALL LETTER O WITH ACUTE > LATIN SMALL LETTER O
    "á": "a",  # LATIN SMALL LETTER A WITH ACUTE > LATIN SMALL LETTER A
    "α": "a",  # GREEK SMALL LETTER ALPHA > LATIN SMALL LETTER A
    "ɑ": "a",  # LATIN SMALL LETTER ALPHA > LATIN SMALL LETTER A
    "ì": "i",  # LATIN SMALL LETTER I WITH GRAVE > LATIN SMALL LETTER I
    "о": "o",  # CYRILLIC SMALL LETTER O > LATIN SMALL LETTER O
    "ñ": "n",  # LATIN SMALL LETTER N WITH TILDE > LATIN SMALL LETTER N
    "ә": "@",  # CYRILLIC SMALL LETTER SCHWA > COMMERCIAL AT
    "ū": "u",  # LATIN SMALL LETTER U WITH MACRON > LATIN SMALL LETTER U
    "т": "t",  # CYRILLIC SMALL LETTER TE > LATIN SMALL LETTER T
    "è": "e",  # LATIN SMALL LETTER E WITH GRAVE > LATIN SMALL LETTER E
    "ģ": "g",  # LATIN SMALL LETTER G WITH CEDILLA > LATIN SMALL LETTER G
    "ú": "u",  # LATIN SMALL LETTER U WITH ACUTE > LATIN SMALL LETTER U
    "ð": "d",  # LATIN SMALL LETTER ETH > LATIN SMALL LETTER D
    "н": "h",  # CYRILLIC SMALL LETTER EN > LATIN SMALL LETTER H
    "р": "r",  # CYRILLIC SMALL LETTER ER > LATIN SMALL LETTER R
    "å": "a",  # LATIN SMALL LETTER A WITH RING ABOVE > LATIN SMALL LETTER A
    "ű": "u",  # LATIN SMALL LETTER U WITH DOUBLE ACUTE > LATIN SMALL LETTER U
    "õ": "o",  # LATIN SMALL LETTER O WITH TILDE > LATIN SMALL LETTER O
    "ô": "o",  # LATIN SMALL LETTER O WITH CIRCUMFLEX > LATIN SMALL LETTER O
    "ò": "o",  # LATIN SMALL LETTER O WITH GRAVE > LATIN SMALL LETTER O
    "м": "m",  # CYRILLIC SMALL LETTER EM > LATIN SMALL LETTER M
    "к": "k",  # CYRILLIC SMALL LETTER KA > LATIN SMALL LETTER K
    "ο": "o",  # GREEK SMALL LETTER OMICRON > LATIN SMALL LETTER O
    "у": "y",  # CYRILLIC SMALL LETTER U > LATIN SMALL LETTER U
    "ķ": "k",  # LATIN SMALL LETTER K WITH CEDILLA > LATIN SMALL LETTER K
    "š": "s",  # LATIN SMALL LETTER S WITH CARON > LATIN SMALL LETTER S
    "ć": "c",  # LATIN SMALL LETTER C WITH ACUTE > LATIN SMALL LETTER C
    "ù": "u",  # LATIN SMALL LETTER U WITH GRAVE > LATIN SMALL LETTER U
    "à": "a",  # LATIN SMALL LETTER A WITH GRAVE > LATIN SMALL LETTER A
    "ø": "o",  # LATIN SMALL LETTER O WITH STROKE > LATIN SMALL LETTER O
    "п": "n",  # CYRILLIC SMALL LETTER PE > LATIN SMALL LETTER N
    "г": "g",  # CYRILLIC SMALL LETTER GHE > LATIN SMALL LETTER G
    "ÿ": "y",  # LATIN SMALL LETTER Y WITH DIAERESIS > LATIN SMALL LETTER Y
    "і": "i",  # CYRILLIC SMALL LETTER BYELORUSSIAN-UKRAINIAN I > LATIN SMALL LETTER I
    "ő": "o",  # LATIN SMALL LETTER O WITH DOUBLE ACUTE > LATIN SMALL LETTER O
    "ɾ": "r",  # LATIN SMALL LETTER R WITH FISHHOOK > LATIN SMALL LETTER R
    "ĺ": "l",  # LATIN SMALL LETTER L WITH ACUTE > LATIN SMALL LETTER L
    "ë": "e",  # LATIN SMALL LETTER E WITH DIAERESIS > LATIN SMALL LETTER E
    "ŕ": "r",  # LATIN SMALL LETTER R WITH ACUTE > LATIN SMALL LETTER R
    "з": "e",  # CYRILLIC SMALL LETTER ZE > LATIN SMALL LETTER E
    "ź": "z",  # LATIN SMALL LETTER Z WITH ACUTE > LATIN SMALL LETTER Z
    "б": "b",  # CYRILLIC SMALL LETTER BE > LATIN SMALL LETTER B
    "σ": "s",  # GREEK SMALL LETTER SIGMA > LATIN SMALL LETTER S
    "ī": "i",  # LATIN SMALL LETTER I WITH MACRON > LATIN SMALL LETTER I
    "ε": "e",  # GREEK SMALL LETTER EPSILON > LATIN SMALL LETTER E
    "ś": "s",  # LATIN SMALL LETTER S WITH ACUTE > LATIN SMALL LETTER S
    "ů": "u",  # LATIN SMALL LETTER U WITH RING ABOVE > LATIN SMALL LETTER U
    "ţ": "t",  # LATIN SMALL LETTER T WITH CEDILLA > LATIN SMALL LETTER T
    "й": "i",  # CYRILLIC SMALL LETTER SHORT I > LATIN SMALL LETTER I
    "đ": "d",  # LATIN SMALL LETTER D WITH STROKE > LATIN SMALL LETTER D
    "ā": "a",  # LATIN SMALL LETTER A WITH MACRON > LATIN SMALL LETTER A
    "ĝ": "g",  # LATIN SMALL LETTER G WITH CIRCUMFLEX > LATIN SMALL LETTER G
    "ν": "v",  # GREEK SMALL LETTER NU > LATIN SMALL LETTER V
    "ň": "n",  # LATIN SMALL LETTER N WITH CARON > LATIN SMALL LETTER N
    "č": "c",  # LATIN SMALL LETTER C WITH CARON > LATIN SMALL LETTER C
    "ł": "l",  # LATIN SMALL LETTER L WITH STROKE > LATIN SMALL LETTER L
    "τ": "t",  # GREEK SMALL LETTER TAU > LATIN SMALL LETTER T
    "η": "e",  # GREEK SMALL LETTER ETA > LATIN SMALL LETTER E
    "ǝ": "e",  # LATIN SMALL LETTER TURNED E > COMMERCIAL AT
    "κ": "k",  # GREEK SMALL LETTER KAPPA > LATIN SMALL LETTER K
    "į": "i",  # LATIN SMALL LETTER I WITH OGONEK > LATIN SMALL LETTER I
    "ρ": "p",  # GREEK SMALL LETTER RHO > LATIN SMALL LETTER P
    "υ": "u",  # GREEK SMALL LETTER UPSILON > LATIN SMALL LETTER U
    "ž": "z",  # LATIN SMALL LETTER Z WITH CARON > LATIN SMALL LETTER Z
    "ō": "o",  # LATIN SMALL LETTER O WITH MACRON > LATIN SMALL LETTER O
    "ａ": "a",  # FULLWIDTH LATIN SMALL LETTER A > LATIN SMALL LETTER A
    "𝐞": "e",  # MATHEMATICAL BOLD SMALL E > LATIN SMALL LETTER E
    "ď": "d",  # LATIN SMALL LETTER D WITH CARON > LATIN SMALL LETTER D
    "ɐ": "a",  # LATIN SMALL LETTER TURNED A > LATIN SMALL LETTER A
    "ｅ": "e",  # FULLWIDTH LATIN SMALL LETTER E > LATIN SMALL LETTER E
    "μ": "u",  # GREEK SMALL LETTER MU > LATIN SMALL LETTER U
    "ą": "a",  # LATIN SMALL LETTER A WITH OGONEK > LATIN SMALL LETTER A
    "𝐚": "a",  # MATHEMATICAL BOLD SMALL A > LATIN SMALL LETTER A
    "ｎ": "n",  # FULLWIDTH LATIN SMALL LETTER N > LATIN SMALL LETTER N
    "ｉ": "i",  # FULLWIDTH LATIN SMALL LETTER I > LATIN SMALL LETTER I
    "π": "n",  # GREEK SMALL LETTER PI > LATIN SMALL LETTER P
    "ｒ": "r",  # FULLWIDTH LATIN SMALL LETTER R > LATIN SMALL LETTER R
    "β": "b",  # GREEK SMALL LETTER BETA > LATIN SMALL LETTER B
    "𝒆": "e",  # MATHEMATICAL BOLD ITALIC SMALL E > LATIN SMALL LETTER E
    "𝐢": "i",  # MATHEMATICAL BOLD SMALL I > LATIN SMALL LETTER I
    "ę": "e",  # LATIN SMALL LETTER E WITH OGONEK > LATIN SMALL LETTER E
    "ʼ": "'",  # MODIFIER LETTER APOSTROPHE > APOSTROPHE
    "𝑒": "e",  # MATHEMATICAL ITALIC SMALL E > LATIN SMALL LETTER E
    "𝐧": "n",  # MATHEMATICAL BOLD SMALL N > LATIN SMALL LETTER N
    "ⁿ": "n",  # SUPERSCRIPT LATIN SMALL LETTER N > LATIN SMALL LETTER N
    "ʇ": "t",  # LATIN SMALL LETTER TURNED T > LATIN SMALL LETTER T
    "ă": "a",  # LATIN SMALL LETTER A WITH BREVE > LATIN SMALL LETTER A
    "ɹ": "r",  # LATIN SMALL LETTER TURNED R > LATIN SMALL LETTER R
    "ｌ": "l",  # FULLWIDTH LATIN SMALL LETTER L > LATIN SMALL LETTER L
    "𝐫": "r",  # MATHEMATICAL BOLD SMALL R > LATIN SMALL LETTER R
    "𝐥": "l",  # MATHEMATICAL BOLD SMALL L > LATIN SMALL LETTER L
    "ῐ": "i",  # GREEK SMALL LETTER IOTA WITH VRACHY > LATIN SMALL LETTER I
    "ɴ": "n",  # LATIN LETTER SMALL CAPITAL N > LATIN SMALL LETTER N
    "𝒂": "a",  # MATHEMATICAL BOLD ITALIC SMALL A > LATIN SMALL LETTER A
    "ǧ": "ğ",  # LATIN SMALL LETTER G WITH CARON > LATIN SMALL LETTER G
    "𝐭": "t",  # MATHEMATICAL BOLD SMALL T > LATIN SMALL LETTER T
    "ά": "a",  # GREEK SMALL LETTER ALPHA WITH TONOS > LATIN SMALL LETTER A
    "𝒊": "i",  # MATHEMATICAL BOLD ITALIC SMALL I > LATIN SMALL LETTER I
    "ί": "i",  # GREEK SMALL LETTER IOTA WITH TONOS > LATIN SMALL LETTER I
    "ｓ": "s",  # FULLWIDTH LATIN SMALL LETTER S > LATIN SMALL LETTER S
    "ż": "z",  # LATIN SMALL LETTER Z WITH DOT ABOVE > LATIN SMALL LETTER Z
    "э": "e",  # CYRILLIC SMALL LETTER E > LATIN SMALL LETTER E
    "𝐨": "o",  # MATHEMATICAL BOLD SMALL O > LATIN SMALL LETTER O
    "ｍ": "m",  # FULLWIDTH LATIN SMALL LETTER M > LATIN SMALL LETTER M
    "ｔ": "t",  # FULLWIDTH LATIN SMALL LETTER T > LATIN SMALL LETTER T
    "𝒕": "t",  # MATHEMATICAL BOLD ITALIC SMALL T > LATIN SMALL LETTER T
    "𝒐": "o",  # MATHEMATICAL BOLD ITALIC SMALL O > LATIN SMALL LETTER O
    "ｄ": "d",  # FULLWIDTH LATIN SMALL LETTER D > LATIN SMALL LETTER D
    "ｋ": "k",  # FULLWIDTH LATIN SMALL LETTER K > LATIN SMALL LETTER K
    "ｏ": "o",  # FULLWIDTH LATIN SMALL LETTER O > LATIN SMALL LETTER O
    "𝑎": "a",  # MATHEMATICAL ITALIC SMALL A > LATIN SMALL LETTER A
    "𝐝": "d",  # MATHEMATICAL BOLD SMALL D > LATIN SMALL LETTER D
    "ω": "o",  # GREEK SMALL LETTER OMEGA > LATIN SMALL LETTER O
    "𝒏": "n",  # MATHEMATICAL BOLD ITALIC SMALL N > LATIN SMALL LETTER N
    "έ": "e",  # GREEK SMALL LETTER EPSILON WITH TONOS > LATIN SMALL LETTER E
    "𝐬": "s",  # MATHEMATICAL BOLD SMALL S > LATIN SMALL LETTER S
    "𝑖": "i",  # MATHEMATICAL ITALIC SMALL I > LATIN SMALL LETTER I
    "ě": "e",  # LATIN SMALL LETTER E WITH CARON > LATIN SMALL LETTER E
    "𝙖": "a",  # MATHEMATICAL SANS-SERIF BOLD ITALIC SMALL A > LATIN SMALL LETTER A
    "𝒔": "s",  # MATHEMATICAL BOLD ITALIC SMALL S > LATIN SMALL LETTER S
    "ᴀ": "A",  # LATIN LETTER SMALL CAPITAL A > LATIN CAPITAL LETTER A
    "ό": "o",  # GREEK SMALL LETTER OMICRON WITH TONOS > LATIN SMALL LETTER O
    "𝒶": "a",  # MATHEMATICAL SCRIPT SMALL A > LATIN SMALL LETTER A
    "ｕ": "u",  # FULLWIDTH LATIN SMALL LETTER U > LATIN SMALL LETTER U
    "𝒓": "r",  # MATHEMATICAL BOLD ITALIC SMALL R > LATIN SMALL LETTER R
    "ｙ": "y",  # FULLWIDTH LATIN SMALL LETTER Y > LATIN SMALL LETTER Y
    "𝑡": "t",  # MATHEMATICAL ITALIC SMALL T > LATIN SMALL LETTER T
    "𝑜": "o",  # MATHEMATICAL ITALIC SMALL O > LATIN SMALL LETTER O
    "ᴇ": "E",  # LATIN LETTER SMALL CAPITAL E > LATIN CAPITAL LETTER E
    "ɯ": "W",  # LATIN SMALL LETTER TURNED M > LATIN CAPITAL LETTER W
    "𝙚": "e",  # MATHEMATICAL SANS-SERIF BOLD ITALIC SMALL E > LATIN SMALL LETTER E
    "𝒍": "l",  # MATHEMATICAL BOLD ITALIC SMALL L > LATIN SMALL LETTER L
    "𝑠": "s",  # MATHEMATICAL ITALIC SMALL S > LATIN SMALL LETTER S
    "ʀ": "R",  # LATIN LETTER SMALL CAPITAL R > LATIN CAPITAL LETTER R
    "ʞ": "k",  # LATIN SMALL LETTER TURNED K > LATIN SMALL LETTER K
    "𝐲": "y",  # MATHEMATICAL BOLD SMALL Y > LATIN SMALL LETTER Y
    "𝑛": "n",  # MATHEMATICAL ITALIC SMALL N > LATIN SMALL LETTER N
    "𝐮": "u",  # MATHEMATICAL BOLD SMALL U > LATIN SMALL LETTER U
    "ɢ": "g",  # LATIN LETTER SMALL CAPITAL G > LATIN SMALL LETTER G
    "𝐦": "m",  # MATHEMATICAL BOLD SMALL M > LATIN SMALL LETTER M
    "𝚎": "e",  # MATHEMATICAL MONOSPACE SMALL E > LATIN SMALL LETTER E
    "𝗮": "a",  # MATHEMATICAL SANS-SERIF BOLD SMALL A > LATIN SMALL LETTER A
    "𝕖": "e",  # MATHEMATICAL DOUBLE-STRUCK SMALL E > LATIN SMALL LETTER E
    "𝙩": "t",  # MATHEMATICAL SANS-SERIF BOLD ITALIC SMALL T > LATIN SMALL LETTER T
    "𝒉": "h",  # MATHEMATICAL BOLD ITALIC SMALL H > LATIN SMALL LETTER H
    "𝙞": "i",  # MATHEMATICAL SANS-SERIF BOLD ITALIC SMALL I > LATIN SMALL LETTER I
    "𝓮": "e",  # MATHEMATICAL BOLD SCRIPT SMALL E > LATIN SMALL LETTER E
    "ɪ": "I",  # LATIN LETTER SMALL CAPITAL I > LATIN CAPITAL LETTER I
    "ʎ": "y",  # LATIN SMALL LETTER TURNED Y > LATIN SMALL LETTER Y
    "𝗲": "e",  # MATHEMATICAL SANS-SERIF BOLD SMALL E > LATIN SMALL LETTER E
    "ｇ": "g",  # FULLWIDTH LATIN SMALL LETTER G > LATIN SMALL LETTER G
    "𝓪": "a",  # MATHEMATICAL BOLD SCRIPT SMALL A > LATIN SMALL LETTER A
    "𝒅": "d",  # MATHEMATICAL BOLD ITALIC SMALL D > LATIN SMALL LETTER D
    "𝑟": "r",  # MATHEMATICAL ITALIC SMALL R > LATIN SMALL LETTER R
    "ř": "r",  # LATIN SMALL LETTER R WITH CARON > LATIN SMALL LETTER R
    "ɔ": "o",  # LATIN SMALL LETTER OPEN O > LATIN SMALL LETTER O
    "𝘢": "a",  # MATHEMATICAL SANS-SERIF ITALIC SMALL A > LATIN SMALL LETTER A
    "ᴏ": "O",  # LATIN LETTER SMALL CAPITAL O > LATIN CAPITAL LETTER O
    "ƃ": "b",  # LATIN SMALL LETTER B WITH TOPBAR > LATIN SMALL LETTER B
    "𝔢": "e",  # MATHEMATICAL FRAKTUR SMALL E > LATIN SMALL LETTER E
    "𝗶": "i",  # MATHEMATICAL SANS-SERIF BOLD SMALL I > LATIN SMALL LETTER I
    "ɥ": "Y",  # LATIN SMALL LETTER TURNED H > LATIN CAPITAL LETTER Y
    "ｚ": "z",  # FULLWIDTH LATIN SMALL LETTER Z > LATIN SMALL LETTER Z
    "ń": "n",  # LATIN SMALL LETTER N WITH ACUTE > LATIN SMALL LETTER N
    "𝚊": "a",  # MATHEMATICAL MONOSPACE SMALL A > LATIN SMALL LETTER A
    "ｈ": "h",  # FULLWIDTH LATIN SMALL LETTER H > LATIN SMALL LETTER H
    "ť": "t",  # LATIN SMALL LETTER T WITH CARON > LATIN SMALL LETTER T
    "𝐛": "b",  # MATHEMATICAL BOLD SMALL B > LATIN SMALL LETTER B
    "𝒄": "c",  # MATHEMATICAL BOLD ITALIC SMALL C > LATIN SMALL LETTER C
    "𝐜": "c",  # MATHEMATICAL BOLD SMALL C > LATIN SMALL LETTER C
    "𝐡": "h",  # MATHEMATICAL BOLD SMALL H > LATIN SMALL LETTER H
    "ʟ": "L",  # LATIN LETTER SMALL CAPITAL L > LATIN CAPITAL LETTER L
    "ⁱ": "i",  # SUPERSCRIPT LATIN SMALL LETTER I > LATIN SMALL LETTER I
    "ｂ": "b",  # FULLWIDTH LATIN SMALL LETTER B > LATIN SMALL LETTER B
    "𝙣": "n",  # MATHEMATICAL SANS-SERIF BOLD ITALIC SMALL N > LATIN SMALL LETTER N
    "ē": "e",  # LATIN SMALL LETTER E WITH MACRON > LATIN SMALL LETTER E
    "ᴛ": "T",  # LATIN LETTER SMALL CAPITAL T > LATIN CAPITAL LETTER T
    "𝑑": "d",  # MATHEMATICAL ITALIC SMALL D > LATIN SMALL LETTER D
    "ʏ": "Y",  # LATIN LETTER SMALL CAPITAL Y > LATIN CAPITAL LETTER Y
    "𝙤": "o",  # MATHEMATICAL SANS-SERIF BOLD ITALIC SMALL O > LATIN SMALL LETTER O
    "𝙧": "r",  # MATHEMATICAL SANS-SERIF BOLD ITALIC SMALL R > LATIN SMALL LETTER R
    "𝑙": "l",  # MATHEMATICAL ITALIC SMALL L > LATIN SMALL LETTER L
    "ή": "e",  # GREEK SMALL LETTER ETA WITH TONOS > LATIN SMALL LETTER E
    "𝒖": "u",  # MATHEMATICAL BOLD ITALIC SMALL U > LATIN SMALL LETTER U
    "𝚘": "o",  # MATHEMATICAL MONOSPACE SMALL O > LATIN SMALL LETTER O
    "ʍ": "w",  # LATIN SMALL LETTER TURNED W > LATIN SMALL LETTER W
    "𝚗": "n",  # MATHEMATICAL MONOSPACE SMALL N > LATIN SMALL LETTER N
    "𝓈": "s",  # MATHEMATICAL SCRIPT SMALL S > LATIN SMALL LETTER S
    "𝘦": "e",  # MATHEMATICAL SANS-SERIF ITALIC SMALL E > LATIN SMALL LETTER E
    "𝖘": "s",  # MATHEMATICAL BOLD FRAKTUR SMALL S > LATIN SMALL LETTER S
    "ζ": "z",  # GREEK SMALL LETTER ZETA > LATIN SMALL LETTER Z
    "𝐤": "k",  # MATHEMATICAL BOLD SMALL K > LATIN SMALL LETTER K
    "𝚒": "i",  # MATHEMATICAL MONOSPACE SMALL I > LATIN SMALL LETTER I
    "𝒚": "y",  # MATHEMATICAL BOLD ITALIC SMALL Y > LATIN SMALL LETTER Y
    "ξ": "x",  # GREEK SMALL LETTER XI > LATIN SMALL LETTER X
    "𝚕": "l",  # MATHEMATICAL MONOSPACE SMALL L > LATIN SMALL LETTER L
    "𝒎": "m",  # MATHEMATICAL BOLD ITALIC SMALL M > LATIN SMALL LETTER M
    "𝖊": "e",  # MATHEMATICAL BOLD FRAKTUR SMALL E > LATIN SMALL LETTER E
    "𝘪": "i",  # MATHEMATICAL SANS-SERIF ITALIC SMALL I > LATIN SMALL LETTER I
    "𝙨": "s",  # MATHEMATICAL SANS-SERIF BOLD ITALIC SMALL S > LATIN SMALL LETTER S
    "𝗼": "o",  # MATHEMATICAL SANS-SERIF BOLD SMALL O > LATIN SMALL LETTER O
    "ᴜ": "U",  # LATIN LETTER SMALL CAPITAL U > LATIN CAPITAL LETTER U
    "ƒ": "f",  # LATIN SMALL LETTER F WITH HOOK > LATIN SMALL LETTER F
    "𝑚": "m",  # MATHEMATICAL ITALIC SMALL M > LATIN SMALL LETTER M
    "𝗻": "n",  # MATHEMATICAL SANS-SERIF BOLD SMALL N > LATIN SMALL LETTER N
    "ύ": "u",  # GREEK SMALL LETTER UPSILON WITH TONOS > LATIN SMALL LETTER U
    "ө": "o",  # CYRILLIC SMALL LETTER BARRED O > LATIN SMALL LETTER O
    "𝘩": "h",  # MATHEMATICAL SANS-SERIF ITALIC SMALL H > LATIN SMALL LETTER H
    "ĸ": "k",  # LATIN SMALL LETTER KRA > LATIN SMALL LETTER K
    "𝗿": "r",  # MATHEMATICAL SANS-SERIF BOLD SMALL R > LATIN SMALL LETTER R
    "𝘴": "s",  # MATHEMATICAL SANS-SERIF ITALIC SMALL S > LATIN SMALL LETTER S
    "𝓻": "r",  # MATHEMATICAL BOLD SCRIPT SMALL R > LATIN SMALL LETTER R
    "𝐠": "g",  # MATHEMATICAL BOLD SMALL G > LATIN SMALL LETTER G
    "ѵ": "y",  # CYRILLIC SMALL LETTER IZHITSA > LATIN SMALL LETTER Y
    "𝚛": "r",  # MATHEMATICAL MONOSPACE SMALL R > LATIN SMALL LETTER R
    "𝕒": "a",  # MATHEMATICAL DOUBLE-STRUCK SMALL A > LATIN SMALL LETTER A
    "𝕣": "r",  # MATHEMATICAL DOUBLE-STRUCK SMALL R > LATIN SMALL LETTER R
    "𝒑": "p",  # MATHEMATICAL BOLD ITALIC SMALL P > LATIN SMALL LETTER P
    "𝗺": "m",  # MATHEMATICAL SANS-SERIF BOLD SMALL M > LATIN SMALL LETTER M
    "𝓁": "l",  # MATHEMATICAL SCRIPT SMALL L > LATIN SMALL LETTER L
    "𝔞": "a",  # MATHEMATICAL FRAKTUR SMALL A > LATIN SMALL LETTER A
    "𝙪": "u",  # MATHEMATICAL SANS-SERIF BOLD ITALIC SMALL U > LATIN SMALL LETTER U
    "𝙢": "m",  # MATHEMATICAL SANS-SERIF BOLD ITALIC SMALL M > LATIN SMALL LETTER M
    "ɟ": "j",  # LATIN SMALL LETTER DOTLESS J WITH STROKE > LATIN SMALL LETTER J
    "𝐩": "p",  # MATHEMATICAL BOLD SMALL P > LATIN SMALL LETTER P
    "𝓽": "t",  # MATHEMATICAL BOLD SCRIPT SMALL T > LATIN SMALL LETTER T
    "𝓇": "r",  # MATHEMATICAL SCRIPT SMALL R > LATIN SMALL LETTER R
    "ḥ": "h",  # LATIN SMALL LETTER H WITH DOT BELOW > LATIN SMALL LETTER H
    "𝕥": "t",  # MATHEMATICAL DOUBLE-STRUCK SMALL T > LATIN SMALL LETTER T
    "ｃ": "c",  # FULLWIDTH LATIN SMALL LETTER C > LATIN SMALL LETTER C
    "𝙙": "d",  # MATHEMATICAL SANS-SERIF BOLD ITALIC SMALL D > LATIN SMALL LETTER D
    "𝙡": "l",  # MATHEMATICAL SANS-SERIF BOLD ITALIC SMALL L > LATIN SMALL LETTER L
    "𝕟": "n",  # MATHEMATICAL DOUBLE-STRUCK SMALL N > LATIN SMALL LETTER N
    "𝓷": "n",  # MATHEMATICAL BOLD SCRIPT SMALL N > LATIN SMALL LETTER N
    "𝓲": "i",  # MATHEMATICAL BOLD SCRIPT SMALL I > LATIN SMALL LETTER I
    "𝗹": "l",  # MATHEMATICAL SANS-SERIF BOLD SMALL L > LATIN SMALL LETTER L
    "𝒇": "f",  # MATHEMATICAL BOLD ITALIC SMALL F > LATIN SMALL LETTER F
    "𝒾": "i",  # MATHEMATICAL SCRIPT SMALL I > LATIN SMALL LETTER I
    "ώ": "w",  # GREEK SMALL LETTER OMEGA WITH TONOS > LATIN SMALL LETTER O
    "𝖆": "a",  # MATHEMATICAL BOLD FRAKTUR SMALL A > LATIN SMALL LETTER A
    "𝑢": "u",  # MATHEMATICAL ITALIC SMALL U > LATIN SMALL LETTER U
    "ү": "u",  # CYRILLIC SMALL LETTER STRAIGHT U > LATIN SMALL LETTER U
    "𝙮": "y",  # MATHEMATICAL SANS-SERIF BOLD ITALIC SMALL Y > LATIN SMALL LETTER Y
    "𝘀": "s",  # MATHEMATICAL SANS-SERIF BOLD SMALL S > LATIN SMALL LETTER S
    "𝘭": "l",  # MATHEMATICAL SANS-SERIF ITALIC SMALL L > LATIN SMALL LETTER L
    "ų": "u",  # LATIN SMALL LETTER U WITH OGONEK > LATIN SMALL LETTER U
    "𝖙": "t",  # MATHEMATICAL BOLD FRAKTUR SMALL T > LATIN SMALL LETTER T
    "𝘰": "o",  # MATHEMATICAL SANS-SERIF ITALIC SMALL O > LATIN SMALL LETTER O
    "𝘯": "n",  # MATHEMATICAL SANS-SERIF ITALIC SMALL N > LATIN SMALL LETTER N
    "𝓃": "n",  # MATHEMATICAL SCRIPT SMALL N > LATIN SMALL LETTER N
    "ė": "e",  # LATIN SMALL LETTER E WITH DOT ABOVE > LATIN SMALL LETTER E
    "𝓸": "o",  # MATHEMATICAL BOLD SCRIPT SMALL O > LATIN SMALL LETTER O
    "ŭ": "u",  # LATIN SMALL LETTER U WITH BREVE > LATIN SMALL LETTER U
    "𝕤": "s",  # MATHEMATICAL DOUBLE-STRUCK SMALL S > LATIN SMALL LETTER S
    "𝘁": "t",  # MATHEMATICAL SANS-SERIF BOLD SMALL T > LATIN SMALL LETTER T
    "𝕝": "l",  # MATHEMATICAL DOUBLE-STRUCK SMALL L > LATIN SMALL LETTER L
    "𝑦": "y",  # MATHEMATICAL ITALIC SMALL Y > LATIN SMALL LETTER Y
    "𝐯": "v",  # MATHEMATICAL BOLD SMALL V > LATIN SMALL LETTER V
    "ј": "j",  # CYRILLIC SMALL LETTER JE > LATIN SMALL LETTER J
    "𝒈": "g",  # MATHEMATICAL BOLD ITALIC SMALL G > LATIN SMALL LETTER G
    "𝓉": "t",  # MATHEMATICAL SCRIPT SMALL T > LATIN SMALL LETTER T
    "𝓂": "m",  # MATHEMATICAL SCRIPT SMALL M > LATIN SMALL LETTER M
    "𝔦": "i",  # MATHEMATICAL FRAKTUR SMALL I > LATIN SMALL LETTER I
    "ț": "t",  # LATIN SMALL LETTER T WITH COMMA BELOW > LATIN SMALL LETTER T
    "𝐰": "w",  # MATHEMATICAL BOLD SMALL W > LATIN SMALL LETTER W
    "𝚖": "m",  # MATHEMATICAL MONOSPACE SMALL M > LATIN SMALL LETTER M
    "𝔬": "o",  # MATHEMATICAL FRAKTUR SMALL O > LATIN SMALL LETTER O
    "𝔥": "h",  # MATHEMATICAL FRAKTUR SMALL H > LATIN SMALL LETTER H
    "𝘶": "u",  # MATHEMATICAL SANS-SERIF ITALIC SMALL U > LATIN SMALL LETTER U
    "ｖ": "v",  # FULLWIDTH LATIN SMALL LETTER V > LATIN SMALL LETTER V
    "𝘂": "u",  # MATHEMATICAL SANS-SERIF BOLD SMALL U > LATIN SMALL LETTER U
    "𝑘": "k",  # MATHEMATICAL ITALIC SMALL K > LATIN SMALL LETTER K
    "𝙝": "h",  # MATHEMATICAL SANS-SERIF BOLD ITALIC SMALL H > LATIN SMALL LETTER H
    "𝑐": "c",  # MATHEMATICAL ITALIC SMALL C > LATIN SMALL LETTER C
    "𝚜": "s",  # MATHEMATICAL MONOSPACE SMALL S > LATIN SMALL LETTER S
    "𝒘": "w",  # MATHEMATICAL BOLD ITALIC SMALL W > LATIN SMALL LETTER W
    "𝓎": "y",  # MATHEMATICAL SCRIPT SMALL Y > LATIN SMALL LETTER Y
    "𝐳": "z",  # MATHEMATICAL BOLD SMALL Z > LATIN SMALL LETTER Z
    "𝐟": "f",  # MATHEMATICAL BOLD SMALL F > LATIN SMALL LETTER F
    "𝑔": "g",  # MATHEMATICAL ITALIC SMALL G > LATIN SMALL LETTER G
    "𝖗": "r",  # MATHEMATICAL BOLD FRAKTUR SMALL R > LATIN SMALL LETTER R
    "ｆ": "f",  # FULLWIDTH LATIN SMALL LETTER F > LATIN SMALL LETTER F
    "𝚍": "d",  # MATHEMATICAL MONOSPACE SMALL D > LATIN SMALL LETTER D
    "𝔱": "t",  # MATHEMATICAL FRAKTUR SMALL T > LATIN SMALL LETTER T
    "𝕠": "o",  # MATHEMATICAL DOUBLE-STRUCK SMALL O > LATIN SMALL LETTER O
    "ｐ": "p",  # FULLWIDTH LATIN SMALL LETTER P > LATIN SMALL LETTER P
    "𝔩": "l",  # MATHEMATICAL FRAKTUR SMALL L > LATIN SMALL LETTER L
    "ɛ": "e",  # LATIN SMALL LETTER OPEN E > LATIN SMALL LETTER E
    "𝖓": "n",  # MATHEMATICAL BOLD FRAKTUR SMALL N > LATIN SMALL LETTER N
    "𝒃": "b",  # MATHEMATICAL BOLD ITALIC SMALL B > LATIN SMALL LETTER B
    "𝓊": "u",  # MATHEMATICAL SCRIPT SMALL U > LATIN SMALL LETTER U
    "𝔯": "r",  # MATHEMATICAL FRAKTUR SMALL R > LATIN SMALL LETTER R
    "𝘵": "t",  # MATHEMATICAL SANS-SERIF ITALIC SMALL T > LATIN SMALL LETTER T
    "𝖚": "u",  # MATHEMATICAL BOLD FRAKTUR SMALL U > LATIN SMALL LETTER U
    "𝘮": "m",  # MATHEMATICAL SANS-SERIF ITALIC SMALL M > LATIN SMALL LETTER M
    "𝕚": "i",  # MATHEMATICAL DOUBLE-STRUCK SMALL I > LATIN SMALL LETTER I
    "ᴍ": "M",  # LATIN LETTER SMALL CAPITAL M > LATIN CAPITAL LETTER M
    "𝘥": "d",  # MATHEMATICAL SANS-SERIF ITALIC SMALL D > LATIN SMALL LETTER D
    "𝓭": "d",  # MATHEMATICAL BOLD SCRIPT SMALL D > LATIN SMALL LETTER D
    "𝚢": "y",  # MATHEMATICAL MONOSPACE SMALL Y > LATIN SMALL LETTER Y
    "𝖑": "l",  # MATHEMATICAL BOLD FRAKTUR SMALL L > LATIN SMALL LETTER L
    "ļ": "l",  # LATIN SMALL LETTER L WITH CEDILLA > LATIN SMALL LETTER L
    "𝓴": "k",  # MATHEMATICAL BOLD SCRIPT SMALL K > LATIN SMALL LETTER K
    "𝑓": "f",  # MATHEMATICAL ITALIC SMALL F > LATIN SMALL LETTER F
    "𝔫": "n",  # MATHEMATICAL FRAKTUR SMALL N > LATIN SMALL LETTER N
    "𝕕": "d",  # MATHEMATICAL DOUBLE-STRUCK SMALL D > LATIN SMALL LETTER D
    "𝒹": "d",  # MATHEMATICAL SCRIPT SMALL D > LATIN SMALL LETTER D
    "𝚝": "t",  # MATHEMATICAL MONOSPACE SMALL T > LATIN SMALL LETTER T
    "𝔂": "y",  # MATHEMATICAL BOLD SCRIPT SMALL Y > LATIN SMALL LETTER Y
    "ị": "i",  # LATIN SMALL LETTER I WITH DOT BELOW > LATIN SMALL LETTER I
    "𝗱": "d",  # MATHEMATICAL SANS-SERIF BOLD SMALL D > LATIN SMALL LETTER D
    "𝒌": "k",  # MATHEMATICAL BOLD ITALIC SMALL K > LATIN SMALL LETTER K
    "𝑝": "p",  # MATHEMATICAL ITALIC SMALL P > LATIN SMALL LETTER P
    "𝙜": "g",  # MATHEMATICAL SANS-SERIF BOLD ITALIC SMALL G > LATIN SMALL LETTER G
    "𝓼": "s",  # MATHEMATICAL BOLD SCRIPT SMALL S > LATIN SMALL LETTER S
    "𝒽": "h",  # MATHEMATICAL SCRIPT SMALL H > LATIN SMALL LETTER H
    "ṭ": "t",  # LATIN SMALL LETTER T WITH DOT BELOW > LATIN SMALL LETTER T
    "𝑏": "b",  # MATHEMATICAL ITALIC SMALL B > LATIN SMALL LETTER B
    "𝖇": "b",  # MATHEMATICAL BOLD FRAKTUR SMALL B > LATIN SMALL LETTER B
    "ᴋ": "K",  # LATIN LETTER SMALL CAPITAL K > LATIN CAPITAL LETTER K
    "ｗ": "w",  # FULLWIDTH LATIN SMALL LETTER W > LATIN SMALL LETTER W
    "𝘺": "y",  # MATHEMATICAL SANS-SERIF ITALIC SMALL Y > LATIN SMALL LETTER Y
    "𝓵": "l",  # MATHEMATICAL BOLD SCRIPT SMALL L > LATIN SMALL LETTER L
    "𝑣": "v",  # MATHEMATICAL ITALIC SMALL V > LATIN SMALL LETTER V
    "𝚏": "f",  # MATHEMATICAL MONOSPACE SMALL F > LATIN SMALL LETTER F
    "𝙠": "k",  # MATHEMATICAL SANS-SERIF BOLD ITALIC SMALL K > LATIN SMALL LETTER K
    "ỳ": "y",  # LATIN SMALL LETTER Y WITH GRAVE > LATIN SMALL LETTER Y
    "𝐱": "x",  # MATHEMATICAL BOLD SMALL X > LATIN SMALL LETTER X
    "𝖐": "k",  # MATHEMATICAL BOLD FRAKTUR SMALL K > LATIN SMALL LETTER K
    "𝖎": "i",  # MATHEMATICAL BOLD FRAKTUR SMALL I > LATIN SMALL LETTER I
    "𝓀": "k",  # MATHEMATICAL SCRIPT SMALL K > LATIN SMALL LETTER K
    "ў": "u",  # CYRILLIC SMALL LETTER SHORT U > LATIN SMALL LETTER U
    "𝖔": "o",  # MATHEMATICAL BOLD FRAKTUR SMALL O > LATIN SMALL LETTER O
    "𝙘": "c",  # MATHEMATICAL SANS-SERIF BOLD ITALIC SMALL C > LATIN SMALL LETTER C
    "ľ": "l",  # LATIN SMALL LETTER L WITH CARON > LATIN SMALL LETTER L
    "ʜ": "H",  # LATIN LETTER SMALL CAPITAL H > LATIN CAPITAL LETTER H
    "𝗈": "o",  # MATHEMATICAL SANS-SERIF SMALL O > LATIN SMALL LETTER O
    "ɠ": "g",  # LATIN SMALL LETTER G WITH HOOK > LATIN SMALL LETTER G
    "ᴅ": "D",  # LATIN LETTER SMALL CAPITAL D > LATIN CAPITAL LETTER D
    "ᴡ": "W",  # LATIN LETTER SMALL CAPITAL W > LATIN CAPITAL LETTER W
    "𝚌": "c",  # MATHEMATICAL MONOSPACE SMALL C > LATIN SMALL LETTER C
    "ɳ": "n",  # LATIN SMALL LETTER N WITH RETROFLEX HOOK > LATIN SMALL LETTER N
    "ņ": "n",  # LATIN SMALL LETTER N WITH CEDILLA > LATIN SMALL LETTER N
    "ọ": "o",  # LATIN SMALL LETTER O WITH DOT BELOW > LATIN SMALL LETTER O
    "𝘇": "z",  # MATHEMATICAL SANS-SERIF BOLD SMALL Z > LATIN SMALL LETTER Z
    "𝙗": "b",  # MATHEMATICAL SANS-SERIF BOLD ITALIC SMALL B > LATIN SMALL LETTER B
    "𝓬": "c",  # MATHEMATICAL BOLD SCRIPT SMALL C > LATIN SMALL LETTER C
    "𝔪": "m",  # MATHEMATICAL FRAKTUR SMALL M > LATIN SMALL LETTER M
    "𝙛": "f",  # MATHEMATICAL SANS-SERIF BOLD ITALIC SMALL F > LATIN SMALL LETTER F
    "ϝ": "w",  # GREEK SMALL LETTER DIGAMMA > LATIN SMALL LETTER W
    "ϓ": "U",  # GREEK UPSILON WITH ACUTE AND HOOK SYMBOL > LATIN CAPITAL LETTER U
    "ϟ": "q",  # GREEK SMALL LETTER KOPPA > LATIN SMALL LETTER Q
    "𝕗": "f",  # MATHEMATICAL DOUBLE-STRUCK SMALL F > LATIN SMALL LETTER F
    "𝕔": "c",  # MATHEMATICAL DOUBLE-STRUCK SMALL C > LATIN SMALL LETTER C
    "𝓶": "m",  # MATHEMATICAL BOLD SCRIPT SMALL M > LATIN SMALL LETTER M
    "𝔤": "g",  # MATHEMATICAL FRAKTUR SMALL G > LATIN SMALL LETTER G
    "𝒛": "z",  # MATHEMATICAL BOLD ITALIC SMALL Z > LATIN SMALL LETTER Z
    "ᴠ": "V",  # LATIN LETTER SMALL CAPITAL V > LATIN CAPITAL LETTER V
    "𝕓": "b",  # MATHEMATICAL DOUBLE-STRUCK SMALL B > LATIN SMALL LETTER B
    "𝓫": "b",  # MATHEMATICAL BOLD SCRIPT SMALL B > LATIN SMALL LETTER B
    "𝓱": "h",  # MATHEMATICAL BOLD SCRIPT SMALL H > LATIN SMALL LETTER H
    "ũ": "u",  # LATIN SMALL LETTER U WITH TILDE > LATIN SMALL LETTER U
    "𝔠": "c",  # MATHEMATICAL FRAKTUR SMALL C > LATIN SMALL LETTER C
    "𝕪": "y",  # MATHEMATICAL DOUBLE-STRUCK SMALL Y > LATIN SMALL LETTER Y
    "𝚔": "k",  # MATHEMATICAL MONOSPACE SMALL K > LATIN SMALL LETTER K
    "𝓾": "u",  # MATHEMATICAL BOLD SCRIPT SMALL U > LATIN SMALL LETTER U
    "𝔶": "y",  # MATHEMATICAL FRAKTUR SMALL Y > LATIN SMALL LETTER Y
    "ƙ": "k",  # LATIN SMALL LETTER K WITH HOOK > LATIN SMALL LETTER K
    "ｊ": "j",  # FULLWIDTH LATIN SMALL LETTER J > LATIN SMALL LETTER J
    "𝕞": "m",  # MATHEMATICAL DOUBLE-STRUCK SMALL M > LATIN SMALL LETTER M
    "𝘆": "y",  # MATHEMATICAL SANS-SERIF BOLD SMALL Y > LATIN SMALL LETTER Y
    "ḫ": "h",  # LATIN SMALL LETTER H WITH BREVE BELOW > LATIN SMALL LETTER H
    "𝚋": "b",  # MATHEMATICAL MONOSPACE SMALL B > LATIN SMALL LETTER B
    "ġ": "g",  # LATIN SMALL LETTER G WITH DOT ABOVE > LATIN SMALL LETTER G
    "ɓ": "b",  # LATIN SMALL LETTER B WITH HOOK > LATIN SMALL LETTER B
    "𝘣": "b",  # MATHEMATICAL SANS-SERIF ITALIC SMALL B > LATIN SMALL LETTER B
    "ᵣ": "r",  # LATIN SUBSCRIPT SMALL LETTER R > LATIN SMALL LETTER R
    "ₒ": "o",  # LATIN SUBSCRIPT SMALL LETTER O > LATIN SMALL LETTER O
    "𝔨": "k",  # MATHEMATICAL FRAKTUR SMALL K > LATIN SMALL LETTER K
    "𝘳": "r",  # MATHEMATICAL SANS-SERIF ITALIC SMALL R > LATIN SMALL LETTER R
    "𝔲": "u",  # MATHEMATICAL FRAKTUR SMALL U > LATIN SMALL LETTER U
    "𝔡": "d",  # MATHEMATICAL FRAKTUR SMALL D > LATIN SMALL LETTER D
    "𝔣": "f",  # MATHEMATICAL FRAKTUR SMALL F > LATIN SMALL LETTER F
    "𝕡": "p",  # MATHEMATICAL DOUBLE-STRUCK SMALL P > LATIN SMALL LETTER P
    "①": "1",  # CIRCLED DIGIT ONE > DIGIT ONE
    "ᴄ": "C",  # LATIN LETTER SMALL CAPITAL C > LATIN CAPITAL LETTER C
    "𝚐": "g",  # MATHEMATICAL MONOSPACE SMALL G > LATIN SMALL LETTER G
    "ʙ": "B",  # LATIN LETTER SMALL CAPITAL B > LATIN CAPITAL LETTER B
    "𝚑": "h",  # MATHEMATICAL MONOSPACE SMALL H > LATIN SMALL LETTER H
    "𝘷": "v",  # MATHEMATICAL SANS-SERIF ITALIC SMALL V > LATIN SMALL LETTER V
    "ʝ": "j",  # LATIN SMALL LETTER J WITH CROSSED-TAIL > LATIN SMALL LETTER J
    "𝑤": "w",  # MATHEMATICAL ITALIC SMALL W > LATIN SMALL LETTER W
    "𝟎": "0",  # MATHEMATICAL BOLD DIGIT ZERO > DIGIT ZERO
    "𝗸": "k",  # MATHEMATICAL SANS-SERIF BOLD SMALL K > LATIN SMALL LETTER K
    "𝗅": "l",  # MATHEMATICAL SANS-SERIF SMALL L > LATIN SMALL LETTER L
    "𝖞": "y",  # MATHEMATICAL BOLD FRAKTUR SMALL Y > LATIN SMALL LETTER Y
    "𝚞": "u",  # MATHEMATICAL MONOSPACE SMALL U > LATIN SMALL LETTER U
    "𝒷": "b",  # MATHEMATICAL SCRIPT SMALL B > LATIN SMALL LETTER B
    "ᵢ": "i",  # LATIN SUBSCRIPT SMALL LETTER I > LATIN SMALL LETTER I
    "ḳ": "k",  # LATIN SMALL LETTER K WITH DOT BELOW > LATIN SMALL LETTER K
    "ₖ": "k",  # LATIN SUBSCRIPT SMALL LETTER K > LATIN SMALL LETTER K
    "ǵ": "g",  # LATIN SMALL LETTER G WITH ACUTE > LATIN SMALL LETTER G
    "𝗴": "g",  # MATHEMATICAL SANS-SERIF BOLD SMALL G > LATIN SMALL LETTER G
    "ₙ": "n",  # LATIN SUBSCRIPT SMALL LETTER N > LATIN SMALL LETTER N
    "ʃ": "S",  # LATIN SMALL LETTER ESH > LATIN CAPITAL LETTER S
    "ĕ": "e",  # LATIN SMALL LETTER E WITH BREVE > LATIN SMALL LETTER E
    "𝓰": "g",  # MATHEMATICAL BOLD SCRIPT SMALL G > LATIN SMALL LETTER G
    "𝙫": "v",  # MATHEMATICAL SANS-SERIF BOLD ITALIC SMALL V > LATIN SMALL LETTER V
    "𝕙": "h",  # MATHEMATICAL DOUBLE-STRUCK SMALL H > LATIN SMALL LETTER H
    "𝖉": "d",  # MATHEMATICAL BOLD FRAKTUR SMALL D > LATIN SMALL LETTER D
    "𝖌": "g",  # MATHEMATICAL BOLD FRAKTUR SMALL G > LATIN SMALL LETTER G
    "𝕨": "w",  # MATHEMATICAL DOUBLE-STRUCK SMALL W > LATIN SMALL LETTER W
    "ɲ": "n",  # LATIN SMALL LETTER N WITH LEFT HOOK > LATIN SMALL LETTER N
    "𝔭": "p",  # MATHEMATICAL FRAKTUR SMALL P > LATIN SMALL LETTER P
    "𝗵": "h",  # MATHEMATICAL SANS-SERIF BOLD SMALL H > LATIN SMALL LETTER H
    "ǐ": "i",  # LATIN SMALL LETTER I WITH CARON > LATIN SMALL LETTER I
    "ṣ": "s",  # LATIN SMALL LETTER S WITH DOT BELOW > LATIN SMALL LETTER S
    "𝖛": "v",  # MATHEMATICAL BOLD FRAKTUR SMALL V > LATIN SMALL LETTER V
    "𝗽": "p",  # MATHEMATICAL SANS-SERIF BOLD SMALL P > LATIN SMALL LETTER P
    "𝙥": "p",  # MATHEMATICAL SANS-SERIF BOLD ITALIC SMALL P > LATIN SMALL LETTER P
    "ŷ": "y",  # LATIN SMALL LETTER Y WITH CIRCUMFLEX > LATIN SMALL LETTER Y
    "𝖺": "a",  # MATHEMATICAL SANS-SERIF SMALL A > LATIN SMALL LETTER A
    "𝗇": "n",  # MATHEMATICAL SANS-SERIF SMALL N > LATIN SMALL LETTER N
    "𝘬": "k",  # MATHEMATICAL SANS-SERIF ITALIC SMALL K > LATIN SMALL LETTER K
    "𝗯": "b",  # MATHEMATICAL SANS-SERIF BOLD SMALL B > LATIN SMALL LETTER B
    "𝔟": "b",  # MATHEMATICAL FRAKTUR SMALL B > LATIN SMALL LETTER B
    "𝒸": "c",  # MATHEMATICAL SCRIPT SMALL C > LATIN SMALL LETTER C
    "ᵤ": "u",  # LATIN SUBSCRIPT SMALL LETTER U > LATIN SMALL LETTER U
    "ạ": "a",  # LATIN SMALL LETTER A WITH DOT BELOW > LATIN SMALL LETTER A
    "ĵ": "j",  # LATIN SMALL LETTER J WITH CIRCUMFLEX > LATIN SMALL LETTER J
    "𝒗": "v",  # MATHEMATICAL BOLD ITALIC SMALL V > LATIN SMALL LETTER V
    "ₑ": "e",  # LATIN SUBSCRIPT SMALL LETTER E > LATIN SMALL LETTER E
    "𝘃": "v",  # MATHEMATICAL SANS-SERIF BOLD SMALL V > LATIN SMALL LETTER V
    "𝘤": "c",  # MATHEMATICAL SANS-SERIF ITALIC SMALL C > LATIN SMALL LETTER C
    "𝕧": "v",  # MATHEMATICAL DOUBLE-STRUCK SMALL V > LATIN SMALL LETTER V
    "ʋ": "v",  # LATIN SMALL LETTER V WITH HOOK > LATIN SMALL LETTER V
    "𝗳": "f",  # MATHEMATICAL SANS-SERIF BOLD SMALL F > LATIN SMALL LETTER F
    "𝘧": "f",  # MATHEMATICAL SANS-SERIF ITALIC SMALL F > LATIN SMALL LETTER F
    "𝒻": "f",  # MATHEMATICAL SCRIPT SMALL F > LATIN SMALL LETTER F
    "𝕦": "u",  # MATHEMATICAL DOUBLE-STRUCK SMALL U > LATIN SMALL LETTER U
    "ǔ": "u",  # LATIN SMALL LETTER U WITH CARON > LATIN SMALL LETTER U
    "𝗁": "h",  # MATHEMATICAL SANS-SERIF SMALL H > LATIN SMALL LETTER H
    "𝖍": "h",  # MATHEMATICAL BOLD FRAKTUR SMALL H > LATIN SMALL LETTER H
    "𝙟": "j",  # MATHEMATICAL SANS-SERIF BOLD ITALIC SMALL J > LATIN SMALL LETTER J
    "ɣ": "g",  # LATIN SMALL LETTER GAMMA > LATIN SMALL LETTER G
    "ɨ": "i",  # LATIN SMALL LETTER I WITH STROKE > LATIN SMALL LETTER I
    "𝗀": "g",  # MATHEMATICAL SANS-SERIF SMALL G > LATIN SMALL LETTER G
    "𝖾": "e",  # MATHEMATICAL SANS-SERIF SMALL E > LATIN SMALL LETTER E
    "ĩ": "i",  # LATIN SMALL LETTER I WITH TILDE > LATIN SMALL LETTER I
    "ẹ": "e",  # LATIN SMALL LETTER E WITH DOT BELOW > LATIN SMALL LETTER E
    "ɗ": "d",  # LATIN SMALL LETTER D WITH HOOK > LATIN SMALL LETTER D
    "𝘸": "w",  # MATHEMATICAL SANS-SERIF ITALIC SMALL W > LATIN SMALL LETTER W
    "𝖜": "w",  # MATHEMATICAL BOLD FRAKTUR SMALL W > LATIN SMALL LETTER W
    "𝙬": "w",  # MATHEMATICAL SANS-SERIF BOLD ITALIC SMALL W > LATIN SMALL LETTER W
    "𝖋": "f",  # MATHEMATICAL BOLD FRAKTUR SMALL F > LATIN SMALL LETTER F
    "ἶ": "i",  # GREEK SMALL LETTER IOTA WITH PSILI AND PERISPOMENI > LATIN SMALL LETTER I
    "ₗ": "l",  # LATIN SUBSCRIPT SMALL LETTER L > LATIN SMALL LETTER L
    "ₜ": "t",  # LATIN SUBSCRIPT SMALL LETTER T > LATIN SMALL LETTER T
    "ϲ": "c",  # GREEK LUNATE SIGMA SYMBOL > LATIN SMALL LETTER C
    "𝒒": "q",  # MATHEMATICAL BOLD ITALIC SMALL Q > LATIN SMALL LETTER Q
    "𝓡": "R",  # MATHEMATICAL BOLD SCRIPT CAPITAL R > LATIN CAPITAL LETTER R
    "𝚟": "v",  # MATHEMATICAL MONOSPACE SMALL V > LATIN SMALL LETTER V
    "𝑧": "z",  # MATHEMATICAL ITALIC SMALL Z > LATIN SMALL LETTER Z
    "４": "4",  # FULLWIDTH DIGIT FOUR > DIGIT FOUR
    "ŏ": "o",  # LATIN SMALL LETTER O WITH BREVE > LATIN SMALL LETTER O
    "𝓋": "v",  # MATHEMATICAL SCRIPT SMALL V > LATIN SMALL LETTER V
    "ḍ": "d",  # LATIN SMALL LETTER D WITH DOT BELOW > LATIN SMALL LETTER D
    "𝕛": "j",  # MATHEMATICAL DOUBLE-STRUCK SMALL J > LATIN SMALL LETTER J
    "ƶ": "z",  # LATIN SMALL LETTER Z WITH STROKE > LATIN SMALL LETTER Z
    "𝕘": "g",  # MATHEMATICAL DOUBLE-STRUCK SMALL G > LATIN SMALL LETTER G
    "ế": "e",  # LATIN SMALL LETTER E WITH CIRCUMFLEX AND ACUTE > LATIN SMALL LETTER E
    "١": "1",  # ARABIC-INDIC DIGIT ONE > DIGIT ONE
    "ħ": "h",  # LATIN SMALL LETTER H WITH STROKE > LATIN SMALL LETTER H
    "②": "2",  # CIRCLED DIGIT TWO > DIGIT TWO
    "ᴊ": "J",  # LATIN LETTER SMALL CAPITAL J > LATIN CAPITAL LETTER J
    "𝔳": "v",  # MATHEMATICAL FRAKTUR SMALL V > LATIN SMALL LETTER V
    "𝓌": "w",  # MATHEMATICAL SCRIPT SMALL W > LATIN SMALL LETTER W
    "𝙯": "z",  # MATHEMATICAL SANS-SERIF BOLD ITALIC SMALL Z > LATIN SMALL LETTER Z
    "ơ": "o",  # LATIN SMALL LETTER O WITH HORN > LATIN SMALL LETTER O
    "ĭ": "i",  # LATIN SMALL LETTER I WITH BREVE > LATIN SMALL LETTER I
    "𝘱": "p",  # MATHEMATICAL SANS-SERIF ITALIC SMALL P > LATIN SMALL LETTER P
    "ₘ": "m",  # LATIN SUBSCRIPT SMALL LETTER M > LATIN SMALL LETTER M
    "𝓿": "v",  # MATHEMATICAL BOLD SCRIPT SMALL V > LATIN SMALL LETTER V
    "𝘄": "w",  # MATHEMATICAL SANS-SERIF BOLD SMALL W > LATIN SMALL LETTER W
    "𝖒": "m",  # MATHEMATICAL BOLD FRAKTUR SMALL M > LATIN SMALL LETTER M
    "ᴘ": "P",  # LATIN LETTER SMALL CAPITAL P > LATIN CAPITAL LETTER P
    "𝖕": "p",  # MATHEMATICAL BOLD FRAKTUR SMALL P > LATIN SMALL LETTER P
    "ŧ": "t",  # LATIN SMALL LETTER T WITH STROKE > LATIN SMALL LETTER T
    "𝗍": "t",  # MATHEMATICAL SANS-SERIF SMALL T > LATIN SMALL LETTER T
    "𝚠": "w",  # MATHEMATICAL MONOSPACE SMALL W > LATIN SMALL LETTER W
    "𝟖": "8",  # MATHEMATICAL BOLD DIGIT EIGHT > DIGIT EIGHT
    "ӓ": "a",  # CYRILLIC SMALL LETTER A WITH DIAERESIS > LATIN SMALL LETTER A
    "ǟ": "a",  # LATIN SMALL LETTER A WITH DIAERESIS AND MACRON > LATIN SMALL LETTER A
    "ɱ": "m",  # LATIN SMALL LETTER M WITH HOOK > LATIN SMALL LETTER M
    "𝐪": "q",  # MATHEMATICAL BOLD SMALL Q > LATIN SMALL LETTER Q
    "ả": "a",  # LATIN SMALL LETTER A WITH HOOK ABOVE > LATIN SMALL LETTER A
    "𝓏": "z",  # MATHEMATICAL SCRIPT SMALL Z > LATIN SMALL LETTER Z
    "ƴ": "y",  # LATIN SMALL LETTER Y WITH HOOK > LATIN SMALL LETTER Y
    "ₕ": "h",  # LATIN SUBSCRIPT SMALL LETTER H > LATIN SMALL LETTER H
    "ǻ": "a",  # LATIN SMALL LETTER A WITH RING ABOVE AND ACUTE > LATIN SMALL LETTER A
    "ủ": "u",  # LATIN SMALL LETTER U WITH HOOK ABOVE > LATIN SMALL LETTER U
    "ộ": "o",  # LATIN SMALL LETTER O WITH CIRCUMFLEX AND DOT BELOW > LATIN SMALL LETTER O
    "ʉ": "u",  # LATIN SMALL LETTER U BAR > LATIN SMALL LETTER U
    "ʊ": "U",  # LATIN SMALL LETTER UPSILON > LATIN CAPITAL LETTER U
    "ḩ": "h",  # LATIN SMALL LETTER H WITH CEDILLA > LATIN SMALL LETTER H
    "𝒙": "x",  # MATHEMATICAL BOLD ITALIC SMALL X > LATIN SMALL LETTER X
    "⑤": "5",  # CIRCLED DIGIT FIVE > DIGIT FIVE
    "⑥": "6",  # CIRCLED DIGIT SIX > DIGIT SIX
    "③": "3",  # CIRCLED DIGIT THREE > DIGIT THREE
    "④": "4",  # CIRCLED DIGIT FOUR > DIGIT FOUR
    "⑦": "7",  # CIRCLED DIGIT SEVEN > DIGIT SEVEN
    "𝗋": "r",  # MATHEMATICAL SANS-SERIF SMALL R > LATIN SMALL LETTER R
    "𝗆": "m",  # MATHEMATICAL SANS-SERIF SMALL M > LATIN SMALL LETTER M
    "𝗎": "u",  # MATHEMATICAL SANS-SERIF SMALL U > LATIN SMALL LETTER U
    "𝘨": "g",  # MATHEMATICAL SANS-SERIF ITALIC SMALL G > LATIN SMALL LETTER G
    "ᵞ": "g",  # MODIFIER LETTER SMALL GREEK GAMMA > LATIN SMALL LETTER G
    "ʑ": "z",  # LATIN SMALL LETTER Z WITH CURL > LATIN SMALL LETTER Z
    "ƨ": "2",  # LATIN SMALL LETTER TONE TWO > DIGIT TWO
    "ǎ": "a",  # LATIN SMALL LETTER A WITH CARON > LATIN SMALL LETTER A
    "𝗉": "p",  # MATHEMATICAL SANS-SERIF SMALL P > LATIN SMALL LETTER P
    "ɽ": "r",  # LATIN SMALL LETTER R WITH TAIL > LATIN SMALL LETTER R
    "ĥ": "h",  # LATIN SMALL LETTER H WITH CIRCUMFLEX > LATIN SMALL LETTER H
    "𝓳": "j",  # MATHEMATICAL BOLD SCRIPT SMALL J > LATIN SMALL LETTER J
    "ȷ": "j",  # LATIN SMALL LETTER DOTLESS J > LATIN SMALL LETTER J
    "𝐣": "j",  # MATHEMATICAL BOLD SMALL J > LATIN SMALL LETTER J
    "𝒋": "j",  # MATHEMATICAL BOLD ITALIC SMALL J > LATIN SMALL LETTER J
    "𝚓": "j",  # MATHEMATICAL MONOSPACE SMALL J > LATIN SMALL LETTER J
    "𝗷": "j",  # MATHEMATICAL SANS-SERIF BOLD SMALL J > LATIN SMALL LETTER J
    "𝘫": "j",  # MATHEMATICAL SANS-SERIF ITALIC SMALL J > LATIN SMALL LETTER J
    "ʄ": "j",  # LATIN SMALL LETTER DOTLESS J WITH STROKE AND HOOK > LATIN SMALL LETTER J
    "ɭ": "l",  # LATIN SMALL LETTER L WITH RETROFLEX HOOK > LATIN SMALL LETTER L
    "𝒿": "j",  # MATHEMATICAL SCRIPT SMALL J > LATIN SMALL LETTER J
    "ʈ": "t",  # LATIN SMALL LETTER T WITH RETROFLEX HOOK > LATIN SMALL LETTER T
    "ổ": "o",  # LATIN SMALL LETTER O WITH CIRCUMFLEX AND HOOK ABOVE > LATIN SMALL LETTER O
    "𝖈": "c",  # MATHEMATICAL BOLD FRAKTUR SMALL C > LATIN SMALL LETTER C
    "ƭ": "t",  # LATIN SMALL LETTER T WITH HOOK > LATIN SMALL LETTER T
    "ậ": "a",  # LATIN SMALL LETTER A WITH CIRCUMFLEX AND DOT BELOW > LATIN SMALL LETTER A
    "ₐ": "a",  # LATIN SUBSCRIPT SMALL LETTER A > LATIN SMALL LETTER A
    "ẓ": "z",  # LATIN SMALL LETTER Z WITH DOT BELOW > LATIN SMALL LETTER Z
    "𝓅": "p",  # MATHEMATICAL SCRIPT SMALL P > LATIN SMALL LETTER P
    "ѧ": "e",  # CYRILLIC SMALL LETTER LITTLE YUS > LATIN SMALL LETTER E
    "ʂ": "s",  # LATIN SMALL LETTER S WITH HOOK > LATIN SMALL LETTER S
    "ŵ": "w",  # LATIN SMALL LETTER W WITH CIRCUMFLEX > LATIN SMALL LETTER W
    "ŗ": "r",  # LATIN SMALL LETTER R WITH CEDILLA > LATIN SMALL LETTER R
    "２": "2",  # FULLWIDTH DIGIT TWO > DIGIT TWO
    "０": "0",  # FULLWIDTH DIGIT ZERO > DIGIT ZERO
    "۹": "9",  # EXTENDED ARABIC-INDIC DIGIT NINE > DIGIT NINE
    "۷": "7",  # EXTENDED ARABIC-INDIC DIGIT SEVEN > DIGIT SEVEN
    "ḏ": "d",  # LATIN SMALL LETTER D WITH LINE BELOW > LATIN SMALL LETTER D
    "ɍ": "r",  # LATIN SMALL LETTER R WITH STROKE > LATIN SMALL LETTER R
    "ỗ": "o",  # LATIN SMALL LETTER O WITH CIRCUMFLEX AND TILDE > LATIN SMALL LETTER O
    "𝗾": "q",  # MATHEMATICAL SANS-SERIF BOLD SMALL Q > LATIN SMALL LETTER Q
    "𝖽": "d",  # MATHEMATICAL SANS-SERIF SMALL D > LATIN SMALL LETTER D
    "ɩ": "i",  # LATIN SMALL LETTER IOTA > LATIN SMALL LETTER I
    "ắ": "a",  # LATIN SMALL LETTER A WITH BREVE AND ACUTE > LATIN SMALL LETTER A
    "𝕜": "k",  # MATHEMATICAL DOUBLE-STRUCK SMALL K > LATIN SMALL LETTER K
    "𝘻": "z",  # MATHEMATICAL SANS-SERIF ITALIC SMALL Z > LATIN SMALL LETTER Z
    "ǿ": "o",  # LATIN SMALL LETTER O WITH STROKE AND ACUTE > LATIN SMALL LETTER O
    "𝓹": "p",  # MATHEMATICAL BOLD SCRIPT SMALL P > LATIN SMALL LETTER P
    "ư": "u",  # LATIN SMALL LETTER U WITH HORN > LATIN SMALL LETTER U
    "ờ": "o",  # LATIN SMALL LETTER O WITH HORN AND GRAVE > LATIN SMALL LETTER O
    "ȡ": "d",  # LATIN SMALL LETTER D WITH CURL > LATIN SMALL LETTER D
    "ề": "e",  # LATIN SMALL LETTER E WITH CIRCUMFLEX AND GRAVE > LATIN SMALL LETTER E
    "ɖ": "d",  # LATIN SMALL LETTER D WITH TAIL > LATIN SMALL LETTER D
    "ȃ": "a",  # LATIN SMALL LETTER A WITH INVERTED BREVE > LATIN SMALL LETTER A
    "𝚙": "p",  # MATHEMATICAL MONOSPACE SMALL P > LATIN SMALL LETTER P
    "ἡ": "e",  # GREEK SMALL LETTER ETA WITH DASIA > LATIN SMALL LETTER E
    "𝕩": "x",  # MATHEMATICAL DOUBLE-STRUCK SMALL X > LATIN SMALL LETTER X
    "ἐ": "e",  # GREEK SMALL LETTER EPSILON WITH PSILI > LATIN SMALL LETTER E
    "ὶ": "i",  # GREEK SMALL LETTER IOTA WITH VARIA > LATIN SMALL LETTER I
    "ᵠ": "f",  # MODIFIER LETTER SMALL GREEK PHI > LATIN SMALL LETTER F
    "𝖿": "f",  # MATHEMATICAL SANS-SERIF SMALL F > LATIN SMALL LETTER F
    "𝟽": "7",  # MATHEMATICAL MONOSPACE DIGIT SEVEN > DIGIT SEVEN
    "ˮ": '"',  # MODIFIER LETTER DOUBLE APOSTROPHE > QUOTATION MARK
    "𝗄": "k",  # MATHEMATICAL SANS-SERIF SMALL K > LATIN SMALL LETTER K
    "ₛ": "s",  # LATIN SUBSCRIPT SMALL LETTER S > LATIN SMALL LETTER S
    "ⱨ": "h",  # LATIN SMALL LETTER H WITH DESCENDER > LATIN SMALL LETTER H
    "ɇ": "e",  # LATIN SMALL LETTER E WITH STROKE > LATIN SMALL LETTER E
    "ĉ": "c",  # LATIN SMALL LETTER C WITH CIRCUMFLEX > LATIN SMALL LETTER C
    "ʁ": "R",  # LATIN LETTER SMALL CAPITAL INVERTED R > LATIN CAPITAL LETTER R
    "ɏ": "y",  # LATIN SMALL LETTER Y WITH STROKE > LATIN SMALL LETTER Y
    "ḿ": "m",  # LATIN SMALL LETTER M WITH ACUTE > LATIN SMALL LETTER M
    "ȅ": "e",  # LATIN SMALL LETTER E WITH DOUBLE GRAVE > LATIN SMALL LETTER E
    "𝗞": "K",  # MATHEMATICAL SANS-SERIF BOLD CAPITAL K > LATIN CAPITAL LETTER K
    "𝗟": "L",  # MATHEMATICAL SANS-SERIF BOLD CAPITAL L > LATIN CAPITAL LETTER L
    "𝓗": "H",  # MATHEMATICAL BOLD SCRIPT CAPITAL H > LATIN CAPITAL LETTER H
    "𝔷": "z",  # MATHEMATICAL FRAKTUR SMALL Z > LATIN SMALL LETTER Z
    "ᴢ": "Z",  # LATIN LETTER SMALL CAPITAL Z > LATIN CAPITAL LETTER Z
    "ἷ": "i",  # GREEK SMALL LETTER IOTA WITH DASIA AND PERISPOMENI > LATIN SMALL LETTER I
    "𝑗": "j",  # MATHEMATICAL ITALIC SMALL J > LATIN SMALL LETTER J
    "ὦ": "w",  # GREEK SMALL LETTER OMEGA WITH PSILI AND PERISPOMENI > LATIN SMALL LETTER O
    "ὰ": "a",  # GREEK SMALL LETTER ALPHA WITH VARIA > LATIN SMALL LETTER A
    "ḱ": "k",  # LATIN SMALL LETTER K WITH ACUTE > LATIN SMALL LETTER K
    "𝖼": "c",  # MATHEMATICAL SANS-SERIF SMALL C > LATIN SMALL LETTER C
    "ớ": "o",  # LATIN SMALL LETTER O WITH HORN AND ACUTE > LATIN SMALL LETTER O
    "𝕸": "M",  # MATHEMATICAL BOLD FRAKTUR CAPITAL M > LATIN CAPITAL LETTER M
    "ɞ": "e",  # LATIN SMALL LETTER CLOSED REVERSED OPEN E > LATIN SMALL LETTER E
    "ｘ": "x",  # FULLWIDTH LATIN SMALL LETTER X > LATIN SMALL LETTER X
    "ƀ": "b",  # LATIN SMALL LETTER B WITH STROKE > LATIN SMALL LETTER B
    "𝗐": "w",  # MATHEMATICAL SANS-SERIF SMALL W > LATIN SMALL LETTER W
    "ầ": "a",  # LATIN SMALL LETTER A WITH CIRCUMFLEX AND GRAVE > LATIN SMALL LETTER A
    "𝖟": "z",  # MATHEMATICAL BOLD FRAKTUR SMALL Z > LATIN SMALL LETTER Z
    "𝚣": "z",  # MATHEMATICAL MONOSPACE SMALL Z > LATIN SMALL LETTER Z
    "ӧ": "o",  # CYRILLIC SMALL LETTER O WITH DIAERESIS > LATIN SMALL LETTER O
    "ӱ": "u",  # CYRILLIC SMALL LETTER U WITH DIAERESIS > LATIN SMALL LETTER U
    "ϋ": "u",  # GREEK SMALL LETTER UPSILON WITH DIALYTIKA > LATIN SMALL LETTER U
    "ʚ": "E",  # LATIN SMALL LETTER CLOSED OPEN E > LATIN CAPITAL LETTER E
    "𝓩": "Z",  # MATHEMATICAL BOLD SCRIPT CAPITAL Z > LATIN CAPITAL LETTER Z
    "𝓔": "E",  # MATHEMATICAL BOLD SCRIPT CAPITAL E > LATIN CAPITAL LETTER E
    "𝓛": "L",  # MATHEMATICAL BOLD SCRIPT CAPITAL L > LATIN CAPITAL LETTER L
    "ὼ": "o",  # GREEK SMALL LETTER OMEGA WITH VARIA > LATIN SMALL LETTER O
    "𝗰": "c",  # MATHEMATICAL SANS-SERIF BOLD SMALL C > LATIN SMALL LETTER C
    "ȳ": "y",  # LATIN SMALL LETTER Y WITH MACRON > LATIN SMALL LETTER Y
    "ṛ": "r",  # LATIN SMALL LETTER R WITH DOT BELOW > LATIN SMALL LETTER R
    "٠": "0",  # ARABIC-INDIC DIGIT ZERO > DIGIT ZERO
    "٢": "2",  # ARABIC-INDIC DIGIT TWO > DIGIT TWO
    "𝓯": "f",  # MATHEMATICAL BOLD SCRIPT SMALL F > LATIN SMALL LETTER F
    "𝔃": "z",  # MATHEMATICAL BOLD SCRIPT SMALL Z > LATIN SMALL LETTER Z
    "𝔴": "w",  # MATHEMATICAL FRAKTUR SMALL W > LATIN SMALL LETTER W
    "ƚ": "l",  # LATIN SMALL LETTER L WITH BAR > LATIN SMALL LETTER L
    "𝘹": "x",  # MATHEMATICAL SANS-SERIF ITALIC SMALL X > LATIN SMALL LETTER X
    "ṡ": "s",  # LATIN SMALL LETTER S WITH DOT ABOVE > LATIN SMALL LETTER S
    "ŝ": "s",  # LATIN SMALL LETTER S WITH CIRCUMFLEX > LATIN SMALL LETTER S
    "ỏ": "o",  # LATIN SMALL LETTER O WITH HOOK ABOVE > LATIN SMALL LETTER O
    "ụ": "u",  # LATIN SMALL LETTER U WITH DOT BELOW > LATIN SMALL LETTER U
    "𝗂": "i",  # MATHEMATICAL SANS-SERIF SMALL I > LATIN SMALL LETTER I
    "ῠ": "u",  # GREEK SMALL LETTER UPSILON WITH VRACHY > LATIN SMALL LETTER U
    "ữ": "u",  # LATIN SMALL LETTER U WITH HORN AND TILDE > LATIN SMALL LETTER U
    "ṽ": "v",  # LATIN SMALL LETTER V WITH TILDE > LATIN SMALL LETTER V
    "ệ": "e",  # LATIN SMALL LETTER E WITH CIRCUMFLEX AND DOT BELOW > LATIN SMALL LETTER E
    "ȟ": "h",  # LATIN SMALL LETTER H WITH CARON > LATIN SMALL LETTER H
    "𝔀": "w",  # MATHEMATICAL BOLD SCRIPT SMALL W > LATIN SMALL LETTER W
    "ẁ": "w",  # LATIN SMALL LETTER W WITH GRAVE > LATIN SMALL LETTER W
    "𝟑": "3",  # MATHEMATICAL BOLD DIGIT THREE > DIGIT THREE
    "𝟔": "6",  # MATHEMATICAL BOLD DIGIT SIX > DIGIT SIX
    "𝖝": "x",  # MATHEMATICAL BOLD FRAKTUR SMALL X > LATIN SMALL LETTER X
    "𝟓": "5",  # MATHEMATICAL BOLD DIGIT FIVE > DIGIT FIVE
    "𝟕": "7",  # MATHEMATICAL BOLD DIGIT SEVEN > DIGIT SEVEN
    "𝟒": "4",  # MATHEMATICAL BOLD DIGIT FOUR > DIGIT FOUR
    "𝓐": "A",  # MATHEMATICAL BOLD SCRIPT CAPITAL A > LATIN CAPITAL LETTER A
    "𝓢": "S",  # MATHEMATICAL BOLD SCRIPT CAPITAL S > LATIN CAPITAL LETTER S
    "๓": "3",  # THAI DIGIT THREE > DIGIT THREE
}
